# Beta App: môi trường thử nghiệm, chạy trên cổng 8080
server {
    listen 8080;
    listen [::]:8080;
    server_name _;

    root /var/www/beta-app/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# Internal App: cổng thông tin nội bộ, chạy trên cổng 8090
server {
    listen 8090;
    listen [::]:8090;
    server_name _;

    root /var/www/internal-app/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
